from .test_create_guarantee_company_view import CreateGuaranteeCompanyViewTest
from .test_create_insurance_company_view import CreateInsuranceCompanyViewTest
from .test_guarantee_company_list_view import GuaranteeCompanyListViewTest
from .test_guarantee_company_view import GuaranteeCompanyViewTest
from .test_insurance_company_list_view import InsuranceCompanyListViewTest
from .test_insurance_company_view import InsuranceCompanyViewTest
