from .test_change_user_password_view import ChangeUserPasswordViewTest
from .test_change_vacancy_user_password_view import ChangeVacancyUserPasswordViewTest
from .test_create_user_view import CreateUserViewTest
from .test_create_vacancy_user_view import CreateVacancyUserViewTest
from .test_login_view import LoginViewTest
from .test_user_list_view import UserListViewTest
from .test_user_view import UserViewTest
from .test_vacancy_user_list_view import VacancyUserListViewTest
