from .create_management_info_view import CreateManagementInfoView
from .delete_management_info_view import DeleteManagementInfoView
from .edit_management_info_view import EditManagementInfoView
from .management_info_list_view import ManagementInfoListView
